config/routes.rb
Rails.application.routes.draw do
  resources :phonebooks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "phonebooks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/phonebook.rb
class Phonebook < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :email_address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/phonebooks_controller.rb
class PhonebooksController < ApplicationController
  before_action :set_phonebook, only: %i[ show edit update destroy ]

  # GET /phonebooks or /phonebooks.json
  def index
    @phonebooks = Phonebook.select("first_name", "last_name", "id").reverse_order
    @contact_count = Phonebook.count

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  # GET /phonebooks/1 or /phonebooks/1.json
  def show
    respond_to do |format|
      format.json {render json: @phonebook, status: :ok}
      format.html
    end
  end

  # GET /phonebooks/new
  def new
    @phonebook = Phonebook.new
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  # GET /phonebooks/1/edit
  def edit
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  # POST /phonebooks or /phonebooks.json
  def create
    @phonebook = Phonebook.new(phonebook_params)

    respond_to do |format|
      if @phonebook.save
        @phonebooks = Phonebook.select("first_name", "last_name", "id").reverse_order
        @contact_count = Phonebook.count
        format.turbo_stream
        format.html { redirect_to phonebook_url(@phonebook), notice: "Phonebook was successfully created." }
        format.json { render :show, status: :created, location: @phonebook }
      else
        format.turbo_stream {render turbo_stream: turbo_stream.update('alert-box', @phonebook.errors.full_messages)}
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phonebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phonebooks/1 or /phonebooks/1.json
  def update
    respond_to do |format|
      if @phonebook.update(phonebook_params)
        @phonebooks = Phonebook.select("first_name", "last_name", "id").reverse_order
        format.turbo_stream
        format.html { redirect_to phonebook_url(@phonebook), notice: "Phonebook was successfully updated." }
        format.json { render :show, status: :ok, location: @phonebook }
      else
        format.turbo_stream {render turbo_stream: turbo_stream.update('alert-box', @phonebook.errors.full_messages)}
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phonebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phonebooks/1 or /phonebooks/1.json
  def destroy
    @phonebook.destroy
    @contact_count = Phonebook.count

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to phonebooks_url, notice: "Phonebook was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phonebook
      @phonebook = Phonebook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phonebook_params
      params.require(:phonebook).permit(:first_name, :last_name, :email_address, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phonebooks_helper.rb
module PhonebooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phonebooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>    
  </head>

  <body>
    <div class="container m-3">
      <%= yield %>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <%= javascript_include_tag "phonebook/index.js", "data-turbolinks-track" => true %>
  </body>
</html>

app/views/phonebooks/_counter.html.erb
<div id="counter" class="card-title text-end"><%=contact_count%></div>

app/views/phonebooks/_form.html.erb
            <%= form_with(model: phonebook, id: "phonebook_form") do |form| %>
              <div class="modal-body">      
                <% if phonebook.errors.any? %>
                  <div style="color: red">
                    <h2><%= pluralize(phonebook.errors.count, "error") %> prohibited this phonebook from being saved:</h2>

                    <ul>
                      <% phonebook.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>

                <div>
                  <%= form.label :first_name, style: "display: block" %>
                  <%= form.text_field :first_name %>
                </div>

                <div>
                  <%= form.label :last_name, style: "display: block" %>
                  <%= form.text_field :last_name %>
                </div>

                <div>
                  <%= form.label :email, style: "display: block" %>
                  <%= form.text_field :email_address %>
                </div>

                <div>
                  <%= form.label :phone, style: "display: block" %>
                  <%= form.text_field :phone %>
                </div>
              </div>
              <div class="modal-footer">
                <div>
                  <button class="btn btn-success" type="submit" data-bs-dismiss="modal">Submit</button>
                </div>
              </div>
            <% end %>

app/views/phonebooks/_phonebook.html.erb
<tr id="<%= dom_id phonebook%>_item">
    <td><%= phonebook.first_name+" "+phonebook.last_name%></td>
    <td><%= phonebook.id%></td>
</tr>

app/views/phonebooks/_phonebook_row.html.erb
<tr id="<%= dom_id phonebook%>_item">
    <td>
        <%= phonebook.first_name+" "+phonebook.last_name%>
    </td>
    <td>
        <div class=btn-group>
            <button class="btn btn-sm btn-secondary" data-id="<%=phonebook.id%>" onclick="methods.btnShowClick(this)">Show</button>
            <button class="btn btn-sm btn-warning" data-id="<%=phonebook.id%>" onclick="methods.btnEditClick(this)">Ubah</button>
            <%= button_to "Hapus", phonebook_path(phonebook), method: :delete, class: "btn btn-sm btn-danger btn-delete", form: {data: {"turbo_confirm": "Apakah Anda Yakin Menghapus Data Ini?"}}%>
        </div>
    </td>
</tr>

app/views/phonebooks/create.turbo_stream.erb
<%= turbo_stream.replace "counter" do%>
    <div id="counter" class="card-title text-end"><%=@contact_count%></div>
<%end%>
<%= turbo_stream.replace "phonebook_row" do%>
    <tbody id="phonebook_row">
        <%= render partial: "phonebook_row", collection: @phonebooks, as: "phonebook" %>
    </tbody>
<%end%>
<%= turbo_stream.replace "phonebook_form" do%>
    <%= render "form", phonebook: Phonebook.new %>
<%end%>
<%= turbo_stream.replace "alert-box" do%>
    <p style="color: red" id="alert-box"></p>
<%end%>

app/views/phonebooks/destroy.turbo_stream.erb
<%= turbo_stream.remove "#{dom_id(@phonebook)}_item" %>
<%= turbo_stream.replace "counter" do%>
    <div id="counter" class="card-title text-end"><%=@contact_count%></div>
<%end%>

app/views/phonebooks/edit.html.erb
<h1>Editing phonebook</h1>

<%= render "form", phonebook: @phonebook %>

<br>

<div>
  <%= link_to "Show this phonebook", @phonebook %> |
  <%= link_to "Back to phonebooks", phonebooks_path %>
</div>

app/views/phonebooks/index.html.erb
<%# <%= turbo_frame_tag "notif_container" do%>
  <%# <%= turbo_frame_tag "modal_container" do%>
  <p style="color: green"><%= notice %></p>
  <p style="color: red" id="alert-box"></p>

  <div class="row">
    <h1>Phonebooks</h1>
  </div>

  <div class="row m-3">
    <div class="card text-bg-success">
      <div class="card-body">
        <div class="card-text">Jumlah Kontak Tersimpan</div>
        <div id="counter" class="card-title text-end"><%=@contact_count%></div>
      </div>
    </div>
  </div>

  <div class="row m-3">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Nama lengkap</th>
          <th>
            <%# <%= link_to "Tambah", new_phonebook_path, class: "btn btn-sm btn-primary btn-create", data:{turbo_frame: "modal_container"}%>
            <button class="btn btn-sm btn-primary" onclick="methods.btnCreateClick(this)">Tambah</button>
          </th>
        </tr>
      </thead>
      <tbody id="phonebook_row">
        <%= render partial: "phonebook_row", collection: @phonebooks, as: "phonebook" %>
      </tbody>
    </table>
  </div>
    <div class="modal" data-bs-backdrop="static" id="modal-form-create">
      <div class="modal-dialog modal-dialog-scrollable">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title">Form</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
              </div>
              <%= render "form", phonebook: Phonebook.new%>
          </div>
      </div>
    </div>
    <div class="modal" data-bs-backdrop="static" id="modal-form-edit">
      <div class="modal-dialog modal-dialog-scrollable">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title">Form</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
              </div>
              <%= render "form", phonebook: Phonebook.new%>
          </div>
      </div>
    </div>
    <div class="modal" id="modal-detail">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Detail Data</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </div>
                <div class="modal-body">
                    <dl class="row" id="detail-field">
                    </dl>
                </div>
            </div>
        </div>
    </div>
  <%# <%end%>
<%# <%end %>

app/views/phonebooks/new.html.erb
<h1>New phonebook</h1>

<%= render "form", phonebook: @phonebook %>

<br>

<div>
  <%= link_to "Back to phonebooks", phonebooks_path %>
</div>

app/views/phonebooks/new.turbo_stream.erb
<%=turbo_stream.prepend "phonebook_form" do%>
    <%= render "form", phonebook: @phonebook%>
<%end%>

app/views/phonebooks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @phonebook %>

<div>
  <%= link_to "Edit this phonebook", edit_phonebook_path(@phonebook) %> |
  <%= link_to "Back to phonebooks", phonebooks_path %>

  <%= button_to "Destroy this phonebook", @phonebook, method: :delete %>
</div>

app/views/phonebooks/update.turbo_stream.erb
<%= turbo_stream.replace "phonebook_row" do%>
    <tbody tbody id="phonebook_row">
        <%= render partial: "phonebook_row", collection: @phonebooks, as: "phonebook" %>
    </tbody>
<%end%>
<%= turbo_stream.replace "alert-box" do%>
    <p style="color: red" id="alert-box"></p>
<%end%>